#!/usr/bin/env bash
#Takes a subdomain and domain to display information about subdomains

function display_subdomain_info {
  record_type=$(dig +short -t $2 $1 | awk '{print $1}')
  destination=$(dig +short $1 | awk '{print $1}')
  echo "The subdomain $1 is a $record_type record and points to $destination"
}

if [ $# -eq 1 ]; then
  domain=$1
  subdomains=(www lb-01 web-01 web-02)
  for subdomain in "${subdomains[@]}"
  do
    display_subdomain_info "$subdomain.$domain" A
  done
elif [ $# -eq 2 ]; then
  display_subdomain_info "$2.$1" A
else
  echo "Usage: $0 <domain> [<subdomain>]"
fi
