#!/usr/bin/env bash

# Check if there are at least 3 parameters
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi

# Extract parameters
path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

# Set default path to SSH key if not provided
if [ -z "$path_to_ssh_key" ]; then
    path_to_ssh_key="$HOME/.ssh/id_rsa"
fi

# Disable strict host key checking
scp_cmd="scp -o StrictHostKeyChecking=no -i $path_to_ssh_key $path_to_file $username@$ip:~"

# Transfer the file
$scp_cmd

# Check the exit status of scp
if [ "$?" -eq 0 ]; then
    echo "File transferred successfully!"
else
    echo "File transfer failed."
fi
