#!/usr/bin/env bash

# update package list
sudo apt-get update

# install nginx
sudo apt-get -y install nginx

# configure nginx to listen on port 80
sudo sed -i 's|listen 80 default_server|listen 80|g' /etc/nginx/sites-available/default

# reload nginx configuration
sudo /etc/init.d/nginx reload

# create HTML file containing "Hello World!"
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

# test that nginx returns "Hello World!" when queried at its root
curl http://localhost
