#!/usr/bin/env bash

# Update package index and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Stop Nginx service
sudo service nginx stop

# Update Nginx configuration file
sudo sed -i '/listen \[::\]:80 default_server/ a\        return 200 "Hello World!";' /etc/nginx/sites-available/default

# Start Nginx service
sudo service nginx start
