#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx

# Check if Nginx is listening on port 80
sudo ss -lnpt | grep ':80'

#Test if Nginx is returning expected response
curl -s http://localhost/

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start

# Check if the index file contains the expected message
cat /var/www/html/index.nginx-debian.html
