#!/usr/bin/env bash
#Redirecting 301 move permanently

apt-get update
apt-get install -y nginx

cat > /etc/nginx/sites-available/redirect << EOF
server {
    listen 80;
    listen [::]:80;
    server_name _;
    return 301 https://https://www.youtube.com/watch?v=QH2-TGUlwu4/;
}
EOF

ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/
nginx -t
systemctl restart nginx
