#!/usr/bin/env bash

# Update and upgrade packages
apt-get update
apt-get -y upgrade

# Install Nginx
apt-get -y install nginx

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx to use the custom 404 page
cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Enable the configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx
systemctl restart nginx
