#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

#Listens to web1 and web2 servers

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 129557-web-01 100.25.211.48:80 check
   server 129557-web-02 18.234.193.238:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
