#!/usr/bin/env bash
#Fixing nginx listening to port 80
cd /etc/nginx/sites-enabled/ || exit;
rm default;
#Symbol link to default file
ln -s /etc/nginx/sites-available/default default;
# Restart Nginx
service nginx restart
