#!/usr/bin/env bash

#This script reads the /etc/passwd file and displays the username, user id, and home directory path for each user

while read -r line; do
  username=$(echo $line | awk -F: '{print $1}')
  userid=$(echo $line | awk -F: '{print $3}')
  homedir=$(echo $line | awk -F: '{print $6}')
  echo "Username: $username"
  echo "User ID: $userid"
  echo "Home directory: $homedir"
done < /etc/passwd

