#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes using while loop

i=0
while [ $i -lt 12 ]
do
    j=1
    while [ $j -lt 60 ]
    do
        echo "$i:$j"
        j=$((j+1))
    done
    i=$((i+1))
done

